# Configuration file for RDF triple-store
#
# adapter: one of adapters supported by ActiveRDF (see ActiveRDF documentation)
# name: a name for the connection
# dbms: type of the real dbms system used to store the triples
# dbname: the name of the real database
# host: dbms host
# port: port used by the dbms
# user: username to access to the dbname
# password: password to access to the dbname

adapter: redland
name: dbl
dbms: mysql
dbname: rt
host: localhost
port: 3306
username: root
password: 12345